# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protob.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protob.Version" do
    optional :value, :string, 1
  end
  add_message "protob.Void" do
  end
end

module Protob
  Version = Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.Version").msgclass
  Void = Google::Protobuf::DescriptorPool.generated_pool.lookup("protob.Void").msgclass
end
