# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: protob.proto for package 'protob'

require 'grpc'
require_relative 'protob_pb'

module Protob
  module BHLIndex
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'protob.BHLIndex'

      rpc :Ver, Void, Version
      rpc :Pages, WithText, stream(Page)
    end

    Stub = Service.rpc_stub_class
  end
end
