version: '3'
services:
  app:
    env_file: ./.env.dev
    build:
      context: .
    volumes:
      - .:/bhlindex/
    container_name: bhlindex
    depends_on:
      - pg
  pg:
    image: postgres:10
    ports:
      - "2345:5432"
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg:
    external: false
