version: '2'
services:
  app:
    build:
      context: .
    container_name: bhlindex
    image: gnames/bhlindex
    depends_on:
      - dgraph
    env_file: .env
    command: ["index"]
  dgraph:
    image: dgraph/dgraph
    volumes:
      - dgraph:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
volumes:
  dgraph:
    external: false
