version: '2'
services:
  app:
    env_file: ./.env
    build:
      context: .
    volumes:
      - .:/go/src/github.com/gnames/bhlindex/
    container_name: bhlindex
    depends_on:
      - pg
  pg:
    image: postgres
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg:
    external: false
