version: '2'
services:
  app:
    build:
      context: .
    volumes:
      - .:/go/src/github.com/GlobalNamesArchitecture/bhlindex/
    container_name: bhlindex
    depends_on:
      - dgraph
    env_file: .env
    # command: bash -c "ginkgo watch"
  dgraph:
    image: dgraph/dgraph
    volumes:
      - dgraph:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    command: dgraph --bindall=true --memory_mb 2048
volumes:
  dgraph:
    external: false
