// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protob.proto

package protob

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MatchType int32

const (
	MatchType_NONE            MatchType = 0
	MatchType_EXACT           MatchType = 1
	MatchType_CANONICAL_EXACT MatchType = 2
	MatchType_CANONICAL_FUZZY MatchType = 3
	MatchType_PARTIAL_EXACT   MatchType = 4
	MatchType_PARTIAL_FUZZY   MatchType = 5
)

var MatchType_name = map[int32]string{
	0: "NONE",
	1: "EXACT",
	2: "CANONICAL_EXACT",
	3: "CANONICAL_FUZZY",
	4: "PARTIAL_EXACT",
	5: "PARTIAL_FUZZY",
}
var MatchType_value = map[string]int32{
	"NONE":            0,
	"EXACT":           1,
	"CANONICAL_EXACT": 2,
	"CANONICAL_FUZZY": 3,
	"PARTIAL_EXACT":   4,
	"PARTIAL_FUZZY":   5,
}

func (x MatchType) String() string {
	return proto.EnumName(MatchType_name, int32(x))
}
func (MatchType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_protob_c436738819333744, []int{0}
}

type Version struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_protob_c436738819333744, []int{0}
}
func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (dst *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(dst, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_protob_c436738819333744, []int{1}
}
func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (dst *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(dst, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type WithText struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithText) Reset()         { *m = WithText{} }
func (m *WithText) String() string { return proto.CompactTextString(m) }
func (*WithText) ProtoMessage()    {}
func (*WithText) Descriptor() ([]byte, []int) {
	return fileDescriptor_protob_c436738819333744, []int{2}
}
func (m *WithText) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithText.Unmarshal(m, b)
}
func (m *WithText) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithText.Marshal(b, m, deterministic)
}
func (dst *WithText) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithText.Merge(dst, src)
}
func (m *WithText) XXX_Size() int {
	return xxx_messageInfo_WithText.Size(m)
}
func (m *WithText) XXX_DiscardUnknown() {
	xxx_messageInfo_WithText.DiscardUnknown(m)
}

var xxx_messageInfo_WithText proto.InternalMessageInfo

func (m *WithText) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type Page struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Offset               int32         `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Text                 []byte        `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	TitleId              string        `protobuf:"bytes,4,opt,name=title_id,json=titleId,proto3" json:"title_id,omitempty"`
	TitlePath            string        `protobuf:"bytes,5,opt,name=title_path,json=titlePath,proto3" json:"title_path,omitempty"`
	Names                []*NameString `protobuf:"bytes,6,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_protob_c436738819333744, []int{3}
}
func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (dst *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(dst, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Page) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Page) GetText() []byte {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *Page) GetTitleId() string {
	if m != nil {
		return m.TitleId
	}
	return ""
}

func (m *Page) GetTitlePath() string {
	if m != nil {
		return m.TitlePath
	}
	return ""
}

func (m *Page) GetNames() []*NameString {
	if m != nil {
		return m.Names
	}
	return nil
}

type NameString struct {
	Value                string    `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Odds                 float32   `protobuf:"fixed32,2,opt,name=odds,proto3" json:"odds,omitempty"`
	Path                 string    `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Curated              bool      `protobuf:"varint,4,opt,name=curated,proto3" json:"curated,omitempty"`
	EditDistance         int32     `protobuf:"varint,5,opt,name=edit_distance,json=editDistance,proto3" json:"edit_distance,omitempty"`
	EditDistanceStem     int32     `protobuf:"varint,6,opt,name=edit_distance_stem,json=editDistanceStem,proto3" json:"edit_distance_stem,omitempty"`
	SourceId             int32     `protobuf:"varint,7,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Match                MatchType `protobuf:"varint,8,opt,name=match,proto3,enum=protob.MatchType" json:"match,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NameString) Reset()         { *m = NameString{} }
func (m *NameString) String() string { return proto.CompactTextString(m) }
func (*NameString) ProtoMessage()    {}
func (*NameString) Descriptor() ([]byte, []int) {
	return fileDescriptor_protob_c436738819333744, []int{4}
}
func (m *NameString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameString.Unmarshal(m, b)
}
func (m *NameString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameString.Marshal(b, m, deterministic)
}
func (dst *NameString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameString.Merge(dst, src)
}
func (m *NameString) XXX_Size() int {
	return xxx_messageInfo_NameString.Size(m)
}
func (m *NameString) XXX_DiscardUnknown() {
	xxx_messageInfo_NameString.DiscardUnknown(m)
}

var xxx_messageInfo_NameString proto.InternalMessageInfo

func (m *NameString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *NameString) GetOdds() float32 {
	if m != nil {
		return m.Odds
	}
	return 0
}

func (m *NameString) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *NameString) GetCurated() bool {
	if m != nil {
		return m.Curated
	}
	return false
}

func (m *NameString) GetEditDistance() int32 {
	if m != nil {
		return m.EditDistance
	}
	return 0
}

func (m *NameString) GetEditDistanceStem() int32 {
	if m != nil {
		return m.EditDistanceStem
	}
	return 0
}

func (m *NameString) GetSourceId() int32 {
	if m != nil {
		return m.SourceId
	}
	return 0
}

func (m *NameString) GetMatch() MatchType {
	if m != nil {
		return m.Match
	}
	return MatchType_NONE
}

func init() {
	proto.RegisterType((*Version)(nil), "protob.Version")
	proto.RegisterType((*Void)(nil), "protob.Void")
	proto.RegisterType((*WithText)(nil), "protob.WithText")
	proto.RegisterType((*Page)(nil), "protob.Page")
	proto.RegisterType((*NameString)(nil), "protob.NameString")
	proto.RegisterEnum("protob.MatchType", MatchType_name, MatchType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BHLIndexClient is the client API for BHLIndex service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BHLIndexClient interface {
	Ver(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Version, error)
	Pages(ctx context.Context, in *WithText, opts ...grpc.CallOption) (BHLIndex_PagesClient, error)
}

type bHLIndexClient struct {
	cc *grpc.ClientConn
}

func NewBHLIndexClient(cc *grpc.ClientConn) BHLIndexClient {
	return &bHLIndexClient{cc}
}

func (c *bHLIndexClient) Ver(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Version, error) {
	out := new(Version)
	err := c.cc.Invoke(ctx, "/protob.BHLIndex/Ver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bHLIndexClient) Pages(ctx context.Context, in *WithText, opts ...grpc.CallOption) (BHLIndex_PagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BHLIndex_serviceDesc.Streams[0], "/protob.BHLIndex/Pages", opts...)
	if err != nil {
		return nil, err
	}
	x := &bHLIndexPagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BHLIndex_PagesClient interface {
	Recv() (*Page, error)
	grpc.ClientStream
}

type bHLIndexPagesClient struct {
	grpc.ClientStream
}

func (x *bHLIndexPagesClient) Recv() (*Page, error) {
	m := new(Page)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BHLIndexServer is the server API for BHLIndex service.
type BHLIndexServer interface {
	Ver(context.Context, *Void) (*Version, error)
	Pages(*WithText, BHLIndex_PagesServer) error
}

func RegisterBHLIndexServer(s *grpc.Server, srv BHLIndexServer) {
	s.RegisterService(&_BHLIndex_serviceDesc, srv)
}

func _BHLIndex_Ver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BHLIndexServer).Ver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protob.BHLIndex/Ver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BHLIndexServer).Ver(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _BHLIndex_Pages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WithText)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BHLIndexServer).Pages(m, &bHLIndexPagesServer{stream})
}

type BHLIndex_PagesServer interface {
	Send(*Page) error
	grpc.ServerStream
}

type bHLIndexPagesServer struct {
	grpc.ServerStream
}

func (x *bHLIndexPagesServer) Send(m *Page) error {
	return x.ServerStream.SendMsg(m)
}

var _BHLIndex_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protob.BHLIndex",
	HandlerType: (*BHLIndexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ver",
			Handler:    _BHLIndex_Ver_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Pages",
			Handler:       _BHLIndex_Pages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protob.proto",
}

func init() { proto.RegisterFile("protob.proto", fileDescriptor_protob_c436738819333744) }

var fileDescriptor_protob_c436738819333744 = []byte{
	// 454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x6f, 0x6f, 0xd3, 0x30,
	0x10, 0x87, 0x9b, 0xe6, 0x4f, 0x93, 0xa3, 0xdb, 0xb2, 0x03, 0x21, 0x33, 0x84, 0x88, 0x82, 0x04,
	0x11, 0xa0, 0x09, 0x95, 0x4f, 0x50, 0xca, 0x10, 0x91, 0x46, 0x56, 0x79, 0xa5, 0xc0, 0xde, 0x44,
	0x5e, 0xed, 0xad, 0x96, 0x96, 0xa4, 0x4a, 0x5c, 0x54, 0xbe, 0x10, 0xdf, 0x12, 0x09, 0xc5, 0x6e,
	0xca, 0x2a, 0xf1, 0xaa, 0xf7, 0x7b, 0xee, 0xa9, 0x73, 0xb6, 0x0e, 0x86, 0xab, 0xba, 0x52, 0xd5,
	0xf5, 0xa9, 0xfe, 0x41, 0xcf, 0xa4, 0xf8, 0x39, 0x0c, 0xe6, 0xa2, 0x6e, 0x64, 0x55, 0xe2, 0x23,
	0x70, 0x7f, 0xb2, 0xbb, 0xb5, 0x20, 0x56, 0x64, 0x25, 0x01, 0x35, 0x21, 0xf6, 0xc0, 0x99, 0x57,
	0x92, 0xc7, 0x11, 0xf8, 0xdf, 0xa4, 0x5a, 0xce, 0xc4, 0x46, 0xed, 0x9b, 0x7e, 0x67, 0xfe, 0xb6,
	0xc0, 0x99, 0xb2, 0x5b, 0x81, 0x87, 0xd0, 0x97, 0x7c, 0x7b, 0x4a, 0x5f, 0x72, 0x7c, 0x0c, 0x5e,
	0x75, 0x73, 0xd3, 0x08, 0x45, 0xfa, 0x91, 0x95, 0xb8, 0x74, 0x9b, 0x10, 0xc1, 0x51, 0x62, 0xa3,
	0x88, 0x1d, 0x59, 0xc9, 0x90, 0xea, 0x1a, 0x9f, 0x80, 0xaf, 0xa4, 0xba, 0x13, 0xb9, 0xe4, 0xc4,
	0xd1, 0x27, 0x0c, 0x74, 0x4e, 0x39, 0x3e, 0x03, 0x30, 0xad, 0x15, 0x53, 0x4b, 0xe2, 0xea, 0x66,
	0xa0, 0xc9, 0x94, 0xa9, 0x25, 0x26, 0xe0, 0x96, 0xac, 0x10, 0x0d, 0xf1, 0x22, 0x3b, 0x79, 0x30,
	0xc2, 0xd3, 0xed, 0x7d, 0x33, 0x56, 0x88, 0x4b, 0x55, 0xcb, 0xf2, 0x96, 0x1a, 0x21, 0xfe, 0x63,
	0x01, 0xfc, 0xa3, 0xff, 0xbf, 0x77, 0x3b, 0x5c, 0xc5, 0x79, 0xa3, 0x47, 0xee, 0x53, 0x5d, 0xb7,
	0x4c, 0x7f, 0xdb, 0xd6, 0xa2, 0xae, 0x91, 0xc0, 0x60, 0xb1, 0xae, 0x99, 0x12, 0x66, 0x5e, 0x9f,
	0x76, 0x11, 0x5f, 0xc0, 0x81, 0xe0, 0x52, 0xe5, 0x5c, 0x36, 0x8a, 0x95, 0x0b, 0xa1, 0x47, 0x76,
	0xe9, 0xb0, 0x85, 0x1f, 0xb7, 0x0c, 0xdf, 0x02, 0xee, 0x49, 0x79, 0xa3, 0x44, 0x41, 0x3c, 0x6d,
	0x86, 0xf7, 0xcd, 0x4b, 0x25, 0x0a, 0x7c, 0x0a, 0x41, 0x53, 0xad, 0xeb, 0x85, 0x7e, 0x9e, 0x81,
	0x96, 0x7c, 0x03, 0x52, 0x8e, 0xaf, 0xc0, 0x2d, 0x98, 0x5a, 0x2c, 0x89, 0x1f, 0x59, 0xc9, 0xe1,
	0xe8, 0xb8, 0x7b, 0x80, 0x2f, 0x2d, 0x9c, 0xfd, 0x5a, 0x09, 0x6a, 0xfa, 0xaf, 0x57, 0x10, 0xec,
	0x18, 0xfa, 0xe0, 0x64, 0x17, 0xd9, 0x59, 0xd8, 0xc3, 0x00, 0xdc, 0xb3, 0xef, 0xe3, 0xc9, 0x2c,
	0xb4, 0xf0, 0x21, 0x1c, 0x4d, 0xc6, 0xd9, 0x45, 0x96, 0x4e, 0xc6, 0xe7, 0xb9, 0x81, 0xfd, 0x7d,
	0xf8, 0xe9, 0xeb, 0xd5, 0xd5, 0x8f, 0xd0, 0xc6, 0x63, 0x38, 0x98, 0x8e, 0xe9, 0x2c, 0xdd, 0x79,
	0xce, 0x7d, 0x64, 0x2c, 0x77, 0x94, 0x83, 0xff, 0xe1, 0xf3, 0x79, 0x5a, 0x72, 0xb1, 0xc1, 0x97,
	0x60, 0xcf, 0x45, 0x8d, 0xc3, 0x6e, 0xbc, 0x76, 0xbb, 0x4e, 0x8e, 0x76, 0xc9, 0x2c, 0x63, 0xdc,
	0xc3, 0x37, 0xe0, 0xb6, 0xdb, 0xd4, 0x60, 0xd8, 0xf5, 0xba, 0xfd, 0x3b, 0xd9, 0xfd, 0xb7, 0x15,
	0xe2, 0xde, 0x3b, 0xeb, 0xda, 0xac, 0xf3, 0xfb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x44, 0xaf,
	0x1c, 0x58, 0xe5, 0x02, 0x00, 0x00,
}
